version: '3'
services:
  framework-nginx:
    build:
      context: psr-framework/docker
      dockerfile: nginx.docker
    volumes:
      - ./psr-framework:/app
    depends_on:
      - framework-php-fpm
    ports:
      - "8090:80"
  framework-php-fpm:
    build:
      context: psr-framework/docker
      dockerfile: php-fpm.docker
    volumes:
      - ./psr-framework:/app
  framework-php-cli:
    build:
      context: psr-framework/docker
      dockerfile: php-cli.docker
    volumes:
      - ./psr-framework:/app
      - composer:/root/.composer/cache

volumes:
  composer: